### ISSUE TITLE
Transfer own content from other social media

### ISSUE THREAD

**Issue by armantorkzaban** [tcfev/forDem#112]
- [ ] twitts
- [ ] fb post
- [ ] instagram posts
This is different to share those contents over forDem. 
- [ ] share to forDem by mentioning the forDem's  bot on those platforms 
related: 
- [ ] Fediverse integration

Resources:
https://github.com/friendica/friendica

**Comment by desputinski** [comment]
Not to forget mastadon! (e.g. https://fosstodon.org)

**Comment by zanzendegi** [comment]
Please continue here: https://github.com/tcfev/forDem/issues/155
