### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by armantorkzaban** [tcfev/forDem#53]
@desputinski please update the readme.md file according to our project description. This can be done in German and English in Mardown format either from browser or from an IDE like VSCode.

**Comment by desputinski** [comment]
Hi Arman, where do i find the reade.md and in what way should I edit it. What is it for?

**Comment by armantorkzaban** [comment]
https://github.com/tcfev/fuerDem/blob/main/README.md
Best would be to edit pull the repository, edit the file, 'commit' changes and 'push' back!
See if you can do this. @agrinpc can assist you. Get more info in DM from me on how to reach him best.

**Comment by armantorkzaban** [comment]
@desputinski, 
you can also edit directly on Github. Just go the link of the file and click on edit, save and commit.

**Comment by armantorkzaban** [comment]
@desputinski to answer your question regarding the read me. At the beginning we can use Read me as an introduction to the project. Later on we can extend it to cover a guide to the software.
You are now using it as a q/a section which is reserved for 'discussion' section. (e.g important discussions can be linked in the readme). 
Please go on an edit the Readme to contain our value, who we are and what we do, like fuerdem.de. Thanks in advance.

**Comment by desputinski** [comment]
Who is the target group for this readme-file? programmers? Way back then, when I used to work with windows software, once in a while I read those. But not in the last years...

**Comment by armantorkzaban** [comment]
This is going to be (part of) our public facing side. Anyone can click on a link on the website to check the code, a programmer might end up reading it and so on.

**Comment by armantorkzaban** [comment]
@emadvote, please mention the #71 in the readme.

**Comment by armantorkzaban** [comment]
I think we are done with this for now. Will close.
