### ISSUE TITLE
Communication protocoll / API to other Networks

### ISSUE THREAD

**Issue by desputinski** [tcfev/forDem#56]
- **IMPORTANT:** Compatible to ActivityPub-Networks: https://en.wikipedia.org/wiki/ActivityPub
- Compatible especially to Mastaon: https://en.wikipedia.org/wiki/Mastodon_(software)
- Compatible especially to Mobilizon: https://mobilizon.org/en/
- Maybe compatible to Wechange?: https://wechange.de/cms/kontakt/

- Make use of the scraping possiblilities fo Librevent: https://github.com/tracking-exposed/librevent
- also see: https://github.com/tracking-exposed

**Comment by desputinski** [comment]
The Idea with the scraping of information is the following:

- Librevent is a browser addon as well as a stand-alone script, that can be used to scrape certain events from facebooks
- So the Idea is, we let this script run lets say once an hour
- The script uses a fake-facebook-account to crawln through facebook
- We create a csv-file with a list of thousands of facebook-pages that have a political target group and thus need to be crawled on a regular basis for furdem. As we are adding those weblinks manually, we can ensure, that the political actors we are collecting dates/events from, act according to our defined values.
- The Script uses this csv-file and scapes all of these events
- All Dates/Events extracted from facebook like that are then automatically sorted along certain keywords. For example: All Events connected to environmental policy, renewable energies and so on are automatically sorted to that category within ForDem
- Fordem presents all of these political events sorted by type of event, political subject and place/town.

**Comment by armantorkzaban** [comment]
@emadvote @zanzendegi

**Comment by emadvote** [comment]
Is there any similar addon for instagram as well? I ask this because the number of Iranian active Instagram active users are not comparable with Facebook. Around 30M active users in Instagram! But Facebook is almost dead in Iran.

**Comment by zanzendegi** [comment]
Facebook is dead in Iran. Instagram will die (my guess). Long live Telegram.

Meta is not respecting privacy when it comes to.

**Comment by desputinski** [comment]
I think Telegram is also not the way to go, as it does not have an open API as far as I know.

**Comment by armantorkzaban** [comment]
@zanzendegi, what are the differences between Signal protocol and Telegram's encryption mechanism?

**Comment by desputinski** [comment]
Also interesting to read about Mobilizon and API: 
https://write.as/simone-robutti/supercharge-your-events-using-mobilizon-and-mobilizon-reshare

**Comment by desputinski** [comment]
Also maybe an inspiration (my old project):
https://archive.org/details/politikvonunten.org_201910

**Comment by desputinski** [comment]
> Is there any similar addon for instagram as well? I ask this because the number of Iranian active Instagram active users are not comparable with Facebook. Around 30M active users in Instagram! But Facebook is almost dead in Iran.

Not yet, but I think it will be possible to fork the librevent-code for that. But does instagram contain dates/events? I thought, it is a photo sharing platform.

**Comment by zanzendegi** [comment]
I suggest closing this issue and continuing here: https://github.com/tcfev/forDem/issues/155

**Comment by desputinski** [comment]
Has there been any contact to the librevent people and the programmers of forDem yet?
I think we roughly know, what kind of events we would like to scrape and then feed into forDem, right? I mean mainly political events posted on facebook. 

Maybe we could also scrape political events from twitter, but I think, this hasn't been implemented in librevent. Not sure, if they are interested in that.

**Comment by desputinski** [comment]
Another question: What exactly is the difference between the Mastodon API and the standard ActivityPub API? Will forDem be compatible to other Fediverse-platforms?
