### ISSUE TITLE
Name/wording of the / for the project (and/or the app itself)

### ISSUE THREAD

**Issue by desputinski** [tcfev/forDem#60]
_Is the name for the project and the app/platform supposed to be identical. Should it be a "German" name (FürDem= Für Demokratie). Or better ForDem maybe? What would be the best name for our target group, or is fürdem already the best name for an app like this?_

Maybe the project itself can be named  FürDem, but the app itself can have a different name. Maybe somehow a name that has some reference to fediverse. I think an English sounding name would be best, if we want to make the app international.

Brainstorming

**- 4Dem**
**- MakeADifference App (MAD)**

- fürDem
- Democracy App (already exists, but is connected to parliamentary politics in Germany only, so not what we want)
- Protest app
- Grassroots app
- Politics Bottom up
- ProtestBook
- Organize
- Democracy Engine (App) [name already exists https://democracyengine.com/how-it-works/]
- Grassroots Engine [GrEn App?]
- Open Grassroots
- OpenRevolution
- Open Society Revolution App (OSR-App)

===============================

Old brainstorming (in German)

Namensideen

-     abhängig vom Anwendungsfall/Zweck unseres Projektes
-     Ideen sammeln (nur aufschreiben, wenn die .de-Domain frei ist):
-     Demokratie Engine (Arbeitstitel)
-     emerdem -> Verknüpfung von Emergenz und Demokratie [Emergenz??]-> wir ermöglichen das Entstehen neuer, unvorhergesehener Kräfte/Strukturen
-     civnet 
-     manyciv

    The spectre (von respect)-> bei spectre muss ich immer an die Bösewichte aus den Bondfilmen denken ...  Das finde ich schick. Ich denke da auch an Spektrum, Perspektivenvielfalt. ich denke auch an Glaskristalle,  bei denen ein Lichtrahl einfällt und dann zu vielen wird. Das würde sich sogar als Logobild eignen :-) Bin aber auch kein Bondfan deswegen andere Assoziationen an der Stelle. Nachtrag: Spectre heißt tatsächlich Geist, Schreckgestenst... Ich meinte spectrum. thespectrum.de kostet 3000 € .org scheint frei

-     oscin (O pen S ource CI vic N etwork) -> verb: osceln
-     Aktionsbündnis Zivilgesellschaft
-     Politik von Unten ([www.politikvonunten.org](http://www.politikvonunten.org/) besteht bereits)
-     FürDemokratie / FürDem (Anfänge von Arman, Marlene und Co, könnte übernommen/ abgeändert werden https://fuerdem.de/)
-     Bezogen auf die beiden Vorschläge zuvor: lieber Akronyme, z. B. ,AkZi' oder ,PovU'
-     Kathrin: Vernetzung Bürger = networking citizens, vielleicht kann aus den Wörtern bzw. Buchstaben ein Name entstehen; Abkürzungen sind teilweise schon in Gebrauch
-     Co-Creation (Domains aber teilweise belegt...)
-     Demo-Network/Netzwerk
-     Partizipativ
-     Worte wie zusammen/gemeinsam/together, future/zukunft
-     Interoperabel beschreibt unsere Plattform auf einen Punkt, ist aber ein blödes Wort
- 

Diskussion:

    Allgemeiner Kommentar Christopher: Ich finde, der Name sollte grundsätzlich nicht kryptisch/voraussetzungsvoll/schwer zu verstehen sein. Die Initiative soll ja massenkompatibel sein... Also lieber klar, einfach und eingängig.

    Kathrin: Evtl. englischer bzw. internationaler Name / Christopher: Finde ich gut! Oder auch ein Name, der sich leicht/logisch/eingängig übertragen läßt zwischen DE und EN

    Charlotte: da schließe ich mich an; ich finde auch sehr lange Namen und ,zu' politische Namen sehr voraussetzungsreich; es geht ja darum, so viele Menschen wie möglich abzuholen und nicht die, die sich sowieso schon engagieren; also tendenziell lieber medienwirksam und massentauglich

    Anne: Die Ideen finde ich sehr gut, aber ich könnte mich jetzt auf Anhieb nicht so recht entscheiden. Aber eine Abkürzung aus einem längeren Begriff scheint mir sehr naheliegend. Wobei ich auch immer das Wort "change" (wie hier in Wechange oder bei change.org) auch sehr sehr gut finde, da ja z.Z. alles im Wandel ist.

Wie heißen ähnliche Projekte?

-     Wechange
-     Wemove
-     Weact
-     Wandelbündnis
-     Campact
-     BewegungsStiftung
-     Politik von unten
-     ATTAC
-     Interventionalistische Linke
-     Avaaz
-     FürDem

Brainstorming Worte zum Kombinieren

-     Demokratie
-     Zivilgesellschaft
-     Protest
-     Empowerment
-     von unten
-     bottom up

**Comment by armantorkzaban** [comment]
I made a basic poll for the name:
https://cloud.transcf.org/apps/polls/s/ZPOSVwhsBRvteQwR

**Comment by desputinski** [comment]
Ok, we have a winner. The name of the project/app will be **ForDem**.

The question is, how it will be spelled. Suggestions:

1. ForDem
2. forDEM
3. forDem
4. ForDem!
5. ¡ForDem
6. fordem
7. FORDEM
8. ForDemApp

**Comment by armantorkzaban** [comment]
ForDem and forDem are my choices. Should we create another poll for that?

**Comment by armantorkzaban** [comment]
A poll was created on this link: https://cloud.transcf.org/apps/polls/s/ZPOSVwhsBRvteQwR
All team members of the time took part. 
ForDem won!
