### ISSUE TITLE
Sponsoring and donating

### ISSUE THREAD

**Issue by Kobin-ts** [tcfev/forDem#75]
...

**Comment by desputinski** [comment]
Is there aready a donation button on the fürdem website? I think there also is a bank account available, or is that only for TCF?

**Comment by desputinski** [comment]
Librepay sounds great. I think we can offer the "bad" options and the good parallel. Bank account is also probably important for the target group of Germans. They are very old fashioned with money :)

**Comment by armantorkzaban** [comment]
> Is there already a donation button on the forDem website? I think there also is a bank account available, or is that only for TCF?

Everything is now on github.com/tcfev. It will also be added to fordem.org and [liberapay.org](https://liberapay.com/tcfev)

**Comment by armantorkzaban** [comment]
@Kobin-ts, we need a page on fordem.org/donation for the same purpose.
