### ISSUE TITLE
Add your availability to ForDem Team calendar

### ISSUE THREAD

**Issue by emadvote** [tcfev/forDem#86]
All team members can have an email address from transcf.org with which they can connect to the organisation's calendar. In order to better plan we need to have a list of team members' time availabilities. We encourage you to get your email address ASAP and set your calendars in 'Fordem Team' which will be shared with you upon creation of the org. email address.
Contact @armantorkzaban for your address, in case you still have not received one.

**Comment by desputinski** [comment]
Is google calendar compatible to standard ics? If yes, ForDem would be compatible to any other standard calendar-tool as well, correct?

**Comment by armantorkzaban** [comment]
@emadvote, please add description.

**Comment by armantorkzaban** [comment]
I think we can close this by now. We have a weekly set, and @drkangl90 and @armantorkzaban have already listed their availability.
@zanzendegi is also informed.
